# docker-compose.yml

volumes:
  faiss_data_volume:

services:
  faiss-server:
    build: .
    container_name: faiss-server
    ports:
      - "8001:8001"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./faiss_server:/app/faiss_server
      - faiss_data_volume:/app/faiss_data:ro
    env_file:
      - .env
    command: ["/opt/conda/envs/faiss_env/bin/uvicorn", "faiss_server.main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]

  api-server:
    build: .
    container_name: api-server
    ports:
      - "8000:8000"
    volumes:
      - ./api_server:/app/api_server
    env_file:
      - .env
    depends_on:
      - faiss-server
    command: ["/opt/conda/envs/faiss_env/bin/uvicorn", "api_server.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
