# environment.yml
name: faiss_env
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - faiss-gpu
  - cudatoolkit=11.8
  - numpy<2.0
  - pip
  - pip:
    - fastapi
    - uvicorn
    - asyncpg
    - python-dotenv
    - httpx
    - python-dateutil # 👈 [수정 완료] 이 줄을 추가했습니다.
